version: '3.7'

services:
  app:
    build: .
    volumes:
     - .:/app
    working_dir: /app
    ports:
     - 8081:8081
    command: ['npm', 'run' ,'local']
    environment:
      PORT: ${PORT}
      MONGO_DB: ${MONGO_DB}
      JWT: ${JWT}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      ENCRYPT_ALGORITHM: ${ENCRYPT_ALGORITHM}
      ENCRYPT_TYPE: ${ENCRYPT_TYPE}
      CORS_ORIGINS: ${CORS_ORIGINS}